### PR TITLE
Remove logic to pass timezone fields with CalendarItem updates

### PR DESCRIPTION
**Pull request by annielcook**
@jhatch28 spent some time looking into this bug https://app.clubhouse.io/nylas/story/55/ews-events-created-on-the-provider-and-then-updated-through-the-api-get-moved-to-14-hours-later and came up with https://phab.nylas.com/D9599. I spent some time looking into it and think one of the solutions that he mentions might be a cleaner way to do this than what he implemented in that diff. This diff removes the logic in exchangelib to pass timezone fields to the provider on updates. This is mentioned in the microsoft docs (included below) which say "To use Coordinated Universal Time (UTC), do not include a TimeZoneContext element, MeetingTimeZone element (Exchange 2007 only), or StartTimeZone and EndTimeZone elements (Exchange 2010 and later) in the CreateItem operation request." Since we always convert times to UTC for syncback, I think that removing the timezone elements will fix the issue of the time shifting.

### CODE REVIEW

**Review by hallamoore — COMMENTED** [review]
I know the exchangelib tests are already in a very sad spot, but could you make sure that this doesn't cause any more of them to fail, or update the ones that do fail? I'd also recommend adding a new test to ensure that we don't accidentally add this logic back in if we merge upstream updates into the repo.

**Comment by annielcook** [comment]
@hallamoore have you run the tests with the account info in a local settings.yml file? I was running them at first without this and was pleased that they were all passing but then I realized that most tests were being skipped because they rely on using an actual account. When I added this file with the test account details, the tests took MUCH longer to run and a lot of them are failing. I am not sure it makes sense for me to spend the time fixing these right now.

**Comment by annielcook** [comment]
🤦‍♀ the tests are SUPER flakey and take so long to run. But I went through each of the tests that failed on my branch that didnt fail on master on one run, and ran them individually and they each passed. I think it would be best to land this and watch closely when we deploy. I also like the idea of adding a test to ensure this functionality doesn't get added back in. But since these tests are tough to figure out, think that could be a separate diff.

**Review by hallamoore — APPROVED** [review]
Alright :woman_shrugging: I'm not super sure about this, like do we still need to return the value as a timezone object, except it should be a UTC timezone object? But if manual testing goes smoothly, then I think it's fine to just run with it.

**Comment by annielcook** [comment]
The parts of the diff I removed were adding the timezone element back into the response that we sent to exchange. Before, we were sending start and end with every update, then we would hit this code and since start and end are in UTC, it would add a timezone element of UTC to the response. However, the quote from the docs that I copied above seems to suggest that if you're using UTC then you should exclude timezone elements. 

Quote came from here: https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-create-appointments-in-a-specific-time-zone-by-using-ews-in-exchange

**Comment by annielcook** [comment]
That recent force push just removed the now unnecessary local import of CalendarItem into both functions.

**Pull request merged**
