### PR TITLE
add example about contact searching

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by khamidou** [comment]
Hi @monperrus — this is a bit late but did you mean to submit this to https://github.com/ecederstrand/exchangelib/ ?

**Comment by monperrus** [comment]
Thanks for your answer. Is https://github.com/ecederstrand/exchangelib/ the official repo?

**Comment by khamidou** [comment]
Yup!

**Comment by monperrus** [comment]
OK, thanks!

I was confused that is the repo is not a fork of the other one. Maybe remove and refork to avoid the same confusion in the future?

**Pull request closed without merging**
